name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  push_to_bsr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
