name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
        working-directory: ./js
      - name: Generate code
        run: npm run build -- --hash=${{ github.sha }}
        working-directory: ./js
      - name: Publish
        run: npm publish --access public
        working-directory: ./js/dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
