name: Validate

on:
  - push
  - pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1.5.0
        with:
          version: 1.5.0
      - uses: bufbuild/buf-lint-action@v1
        continue-on-error: true
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://github.com/$GITHUB_REPOSITORY.git#branch=main"
